# PactFlow Bi-Directional Provider Worfklow

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: pact_templates
      type: github
      name: you54f/azure-pipelines-templates
      endpoint: azure-templates-pact-github # azure service connection to allow read-only access to github repo
      # ref: refs/heads/templates # point to a commit / branch / tag

variables:
  - name: application_name
    value: pactflow-example-bi-directional-provider-dotnet
  - name: PACT_BROKER_BASE_URL
    value: https://testdemo.pactflow.io
  - template: templates/azure_pact_variables.yml@pact_templates
  # - name: contract
    # value: "example-bi-directional-provider-dotnet/example-bi-directional-provider-dotnet/swagger.json"
  - name: contract_content_type
    value: "application/json" # optional, defaults to application/yml
  - name: verification_results
    value: "example-bi-directional-provider-dotnet/report.txt"
  - name: verifier
    value: "schemathesis"

steps:
- checkout: self
- task: UseDotNet@2
  inputs:
    version: '8.0.406'
- script: make publish_dll
  displayName: ✅  Generate OpenAPI with SwashBuckle
  workingDirectory: example-bi-directional-provider-dotnet
- script: make test
  displayName: ✅  Test
  workingDirectory: example-bi-directional-provider-dotnet
- template: templates/azure_pact_publish_provider_contract.yml@pact_templates
  parameters:
    # application_name: $(PACTICIPANT) # The pacticipant name of which the branch belongs to
    token: $(PACT_BROKER_TOKEN)
    # contract: example-bi-directional-provider-dotnet/example-bi-directional-provider-dotnet/swagger.json
    # contract_content_type: application/yaml # optional, defaults to application/yml
    # verification_results: example-bi-directional-provider-dotnet/report.txt
    # verifier: schemathesis
- ${{ if eq(variables['Agent.JobStatus'], 'Failed') }}:
  - template: templates/azure_pact_publish_provider_contract.yml@pact_templates
    parameters:
      # application_name: $(PACTICIPANT) # The pacticipant name of which the branch belongs to
      token: $(PACT_BROKER_TOKEN)
      # contract: example-bi-directional-provider-dotnet/example-bi-directional-provider-dotnet/swagger.json
      # contract_content_type: application/yaml # optional, defaults to application/yml
      # verification_results: example-bi-directional-provider-dotnet/report.txt
      # verifier: schemathesis
      verification_exit_code: 1 # defaults to 0 (success)

- template: templates/azure_pact_can_i_deploy.yml@pact_templates
  parameters:
    to_environment: production
    # application_name: $(PACTICIPANT)
    token: $(PACT_BROKER_TOKEN)
    retry_while_unknown: 5
    retry_interval: 10
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - template: templates/azure_pact_record_deployment.yml@pact_templates
    parameters:
      environment: production
      # application_name: $(PACTICIPANT)
      token: $(PACT_BROKER_TOKEN)
